spring:
  application:
    name: spring-cloud-service-ticket
server:
  port: 12004
  servlet:
    context-path: /service-ticket

eureka:
  #标记客户端，向注册中心注册
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/