spring:
  application:
    name: spring-cloud-service-user
server:
  port: 12002
  servlet:
    context-path: /service-user

eureka:
  #标记客户端，向注册中心注册
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/